version: "3.7"

services:

  db:
    env_file:
      - .env
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${USER_NAME}
      POSTGRES_PASSWORD: 1
      PGDATA: /var/lib/postgresql/data
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    ports:
      - "5432:5432"

  web_service:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app/
    depends_on:
      - db
      - pgadmin



  pgadmin:
    env_file:
      - .env
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_DEF_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_DEF_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "db:pgsql-server"

volumes:
  db-data:
  pgadmin-data: